exercism/racket

gigasecond/example.rkt
list-ops/example.rkt
rna-transcription/example.rkt
word-count/example.rkt

http://docs.racket-lang.org/style/Units_of_Code.html#%28part._.Modules_and_their_.Interfaces%29

Racket style

---

anagram/anagram-test.rkt
anagram/example.rkt

resolves failed travis ci build for https://github.com/exercism/xracket/pull/16

resolves failed build

---

config.json
grep/example.rkt
grep/grep-test.rkt
grep/grep.rkt

Now with an updated `config.json` and `module+ test`.

Add grep exercise

---

config.json
docs/INSTALLATION.md
docs/RESOURCES.md
docs/TESTS.md

Added docs for api v3

---

difference-of-squares/example.rkt

Idiomatic Racket using sequences and comprehensions.

---

SETUP.md

Fix instructions for running tests via the commandline.

---

docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/RESOURCES.md
docs/TESTS.md

also resolves #34 and closes #32

clean up docs for x-api v3

---

.travis.yml
config.json

The YAML was not quite valid. Travis can read it
and wasn't complaining, but this ensures that the YAML
is clean.

Normalize YAML in Travis CI config

---

word-count/word-count-test.rkt

test word-count hash content equality, not hash state

---

config.json
roman-numerals/example.rkt
roman-numerals/roman-numerals-test.rkt
roman-numerals/roman-numerals.rkt

Test cases are identical to the Ruby version.

Add Roman Numerals exercise

---

bin/check-exercises.sh
config.json
exercises/allergies/allergies-test.rkt
exercises/allergies/example.rkt

Not thrilled with the way that testing is done in exercism for racket...
I've moved a number of tests over to test-case + check-true/false and
refactored into lists-equiv? that uses check-equal?. Revamping the other
tests will come some other time.

Added first pass at allergies problem.

---

config.json
exercises/scrabble-score/example.rkt
exercises/scrabble-score/scrabble-score-test.rkt
exercises/scrabble-score/scrabble-score.rkt

This is my first contribution to exercism... I read the contributor's doco and was overwhelmed by all the API stuff that doesn't seem relevant? I can't tell. Pushing PR sooner rather than later to get feedback.

Added first pass at scrabble-score for racket.

---

config.json

This is just "step 1" from #58, "where difficulty is 1 and topics is empty".

add initial 'exercises' key to config.json (see #58)

---

README.md

Updated to match latest conventions to the best of my knowledge

Reworked exercism/rust README.md

---

config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/collatz-conjecture-test.rkt
exercises/collatz-conjecture/collatz-conjecture.rkt
exercises/collatz-conjecture/example.rkt

Implement exercise collatz-conjecture

---

.travis.yml
config.json
exercises/meetup/README.md
exercises/meetup/example.rkt
exercises/meetup/meetup-test.rkt
exercises/meetup/meetup.rkt

This PR is an effort to fix the issues with https://github.com/exercism/racket/pull/56.  I added ```README.md```, the template file ```meetup.rkt``` and reformatted ```config.json```

Zenspider mbertheau fix meetup

---

config.json
docs/ABOUT.md

This also relates to https://github.com/exercism/racket/issues/95.  It adds some more documentation to the config and ABOUT files.

Adding some blurb

---

config.json

This is a minor PR and my first go at contributing to this repo.  It's hopefully straightforward.  I noticed that running configlet tree produced an error complaining there was no core track defined.  So I looked at the current exercism racket track and copied that.
Hope it helps.

Define core track

---

exercises/bob/README.md
exercises/gigasecond/README.md
exercises/hamming/README.md
exercises/list-ops/README.md
exercises/perfect-numbers/README.md
exercises/rna-transcription/README.md
exercises/say/README.md
exercises/two-fer/README.md

Update out-of-date READMEs using configlet

update READMEs using configlet

---

config.json
exercises/affine-cipher/.meta/hints.md
exercises/affine-cipher/README.md
exercises/affine-cipher/affine-cipher-test.rkt
exercises/affine-cipher/affine-cipher.rkt
exercises/affine-cipher/example.rkt

Hi - first attempt at making a Racket problem submission for your site. I tried to add all of the tests in the problem-specifications for the problem.

New Racket implementation of the "affine-cipher" problem.

---

config.json
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/armstrong-numbers-test.rkt
exercises/armstrong-numbers/armstrong-numbers.rkt
exercises/armstrong-numbers/example.rkt

New, simple problem for the track.
Please let me know if you would like anything to be changed.

Armstrong numbers

---

config.json
exercises/isogram/README.md
exercises/isogram/example.rkt
exercises/isogram/isogram-test.rkt
exercises/isogram/isogram.rkt

New exercise, comments on style or comment appreciated.

Isogram Exercism

---

exercises/reverse-string/example.rkt

I added @guygastineau's elegant suggestion from another comment thread. I hope that he doesn't mind.

Added more elegant example solution to reverse-string.

---

exercises/acronym/acronym-test.rkt
exercises/acronym/example.rkt

@guygastineau motivated me to help with getting the tests up to date.

Updated "acronym" tests to canonical-data.json v1.7.0

---

exercises/scrabble-score/scrabble-score-test.rkt

Relatively minor edits to the tests.

Updated "scrabble-score" tests to canonical-data.json v1.1.0

---

exercises/two-fer/two-fer-test.rkt

The only change was adding the comment.

Updated "two-fer" tests to canonical-data.json v1.2.0

---

exercises/word-count/example.rkt
exercises/word-count/word-count-test.rkt

Updated to the most recent version of the tests, I had to modify the example so that it worked with the tests.

Updated "word-count" tests to canonical-data.json v1.4.0

---

config.json
exercises/atbash-cipher/.meta/hints.md
exercises/atbash-cipher/README.md
exercises/atbash-cipher/atbash-cipher-test.rkt
exercises/atbash-cipher/atbash-cipher.rkt
exercises/atbash-cipher/example.rkt

Ok - started from fresh fork, pasted the files back in. Hopefully this removed any remaining debris from my end.

Atbash cipher exercise implementation.

---

config.json
exercises/affine-cipher/.meta/hints.md
exercises/robot-name/.meta/hints.md
exercises/robot-name/README.md
exercises/robot-name/example.rkt
exercises/robot-name/robot-name-test.rkt
exercises/robot-name/robot-name.rkt

This one seemed to need objects, and none of the other exercises in the track used objects ... or I might have tried to copy some aspects. I also didn't see a list of standard test cases, so I just made a few up.
In summary, I went out on a limb with this one, and if anyone has suggestions for making it better - I'd be happy to change this PR.

New exercise: "robot name"

---

exercises/phone-number/example.rkt
exercises/phone-number/phone-number-test.rkt
exercises/phone-number/phone-number.rkt

This is a bit more than an "update," version 1.7.0 sort of changed everything from the previous version of the problem. It was largely a reimplementation.
Please let me know if you'd like anything changed or clarified.

Updated "phone-number" to canonical-data.json v1.7.0

---

config.json
exercises/variable-length-quantity/README.md
exercises/variable-length-quantity/example.rkt
exercises/variable-length-quantity/variable-length-quantity-test.rkt
exercises/variable-length-quantity/variable-length-quantity.rkt

Yes!  You can do byte-operations in Racket!!  Not yet done but hopefully I'll finish tonight!

Implementing the "Variable Length Quantity" Exercise

---

.github/workflows/ci.yml

- ci: upgrade setup-racket workflow
- ci: run on Racket 8.2

ci: upgrade

---

exercises/practice/hamming/hamming.rkt
exercises/practice/isogram/isogram.rkt
exercises/practice/leap/leap.rkt
exercises/practice/list-ops/list-ops.rkt
exercises/practice/meetup/meetup.rkt

adds or updates for stub implementations which throw an error

---

exercises/practice/say/say.rkt
exercises/practice/scrabble-score/scrabble-score.rkt
exercises/practice/two-fer/two-fer.rkt
exercises/practice/variable-length-quantity/variable-length-quantity.rkt
exercises/practice/word-count/word-count.rkt

exercises s-w: add or update for stub implementations

---

exercises/practice/bob/bob.rkt
exercises/practice/collatz-conjecture/collatz-conjecture.rkt
exercises/practice/difference-of-squares/difference-of-squares.rkt
exercises/practice/etl/etl.rkt
exercises/practice/gigasecond/gigasecond.rkt
exercises/practice/grains/grains.rkt
exercises/practice/grep/grep.rkt

More exercises updated with stubs so code is runnable immediately after download, say via `raco test .`

for exercises b-g: add or update for stub implementations which throw an error

---

exercises/practice/nucleotide-count/nucleotide-count.rkt
exercises/practice/perfect-numbers/perfect-numbers.rkt
exercises/practice/raindrops/raindrops.rkt
exercises/practice/reverse-string/reverse-string.rkt
exercises/practice/rna-transcription/rna-transcription.rkt
exercises/practice/robot-name/robot-name.rkt
exercises/practice/roman-numerals/roman-numerals.rkt

for exercises n-r: add or update for stub implementations

---

.github/workflows/ci.yml

Also update racket install from `Bogdanp/setup-racket@<CHANGESET>` to `Bogdanp/setup-racket@v1.9` per readme

Github Actions Updated: Test on 8.5 & 8.6

---

config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/sublist/.docs/instructions.md
exercises/practice/sublist/.meta/config.json
exercises/practice/sublist/.meta/example.rkt
exercises/practice/sublist/sublist-test.rkt
exercises/practice/sublist/sublist.rkt

Copied (from Elixir track) and implemented `Sublist` exercise. Also, quick fix to `matching-brackets` config.

New Exercise: Sublist

---

exercises/practice/acronym/.meta/config.json
exercises/practice/affine-cipher/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/grep/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/reverse-string/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/say/.meta/config.json
exercises/practice/sublist/.meta/config.json
exercises/practice/two-fer/.meta/config.json

This brings in recent improvements to the metadata for all practice exercises.

Sync metadata with problem-specifications

---

config.json
exercises/practice/alphametics/.docs/instructions.md
exercises/practice/alphametics/.meta/config.json
exercises/practice/alphametics/.meta/example.rkt
exercises/practice/alphametics/.meta/tests.toml
exercises/practice/alphametics/alphametics-test.rkt
exercises/practice/alphametics/alphametics.rkt

@ErikSchierboom - Here's my work for #247. I'm happy to make revisions where needed. Thank you for your patience.

Add the Alphametics exercise (#248)

---

exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/gigasecond/.meta/tests.toml
exercises/practice/gigasecond/gigasecond-test.rkt

Update gigasecond docs and test

---

exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/matching-brackets/matching-brackets-test.rkt

Sync matching brackets and update tests

---

config.json
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.meta/config.json
exercises/practice/resistor-color/.meta/example.rkt
exercises/practice/resistor-color/.meta/tests.toml
exercises/practice/resistor-color/resistor-color-test.rkt
exercises/practice/resistor-color/resistor-color.rkt

Reintroduction of previous PR with edits

Add resistor-color exercise

---

exercises/practice/accumulate/.meta/config.json
exercises/practice/etl/.meta/config.json

Update missing authors

---

bin/fetch-configlet.ps1

I pulled the latest contents from https://github.com/exercism/configlet/blob/main/scripts/fetch-configlet.ps1

Add fetch-configlet.ps1

---

exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/allergies-test.rkt

Fixed a minor typo and added a new test from the problem specifications. Related to #274

Update allergies tests

---

exercises/practice/alphametics/.meta/config.json
exercises/practice/resistor-color/.meta/config.json

configlet fmt

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/example.rkt
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/dnd-character-test.rkt
exercises/practice/dnd-character/dnd-character.rkt

Add dnd-character

---

config.json
exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/protein-translation/.meta/config.json
exercises/practice/protein-translation/.meta/example.rkt
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/protein-translation-test.rkt
exercises/practice/protein-translation/protein-translation.rkt

I put 3 as difficulty for this one because it mixes `case`, `error`, string manipulation and list aggregation.
Nothing else to report, let me know what you think. 😉
@BNAndras

Add protein translation exercise (#297)

---

exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/anagram-test.rkt

Add reimplemented anagram test

---

exercises/practice/bob/bob-test.rkt
exercises/practice/robot-name/robot-name-test.rkt

Minor typos that should be merged as no important changes.

Minor typo fixes

---

config.json
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/pangram/.meta/config.json
exercises/practice/pangram/.meta/example.rkt
exercises/practice/pangram/.meta/tests.toml
exercises/practice/pangram/pangram-test.rkt
exercises/practice/pangram/pangram.rkt

Add pangram exercise

---

config.json
exercises/practice/zebra-puzzle/.docs/instructions.md
exercises/practice/zebra-puzzle/.meta/config.json
exercises/practice/zebra-puzzle/.meta/example.rkt
exercises/practice/zebra-puzzle/.meta/tests.toml
exercises/practice/zebra-puzzle/zebra-puzzle-test.rkt
exercises/practice/zebra-puzzle/zebra-puzzle.rkt

Tests, stub code, example implementation.

Add the Zebra Puzzle as a practice exercise.

---

config.json
exercises/practice/two-bucket/.docs/instructions.md
exercises/practice/two-bucket/.meta/config.json
exercises/practice/two-bucket/.meta/example.rkt
exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/two-bucket-test.rkt
exercises/practice/two-bucket/two-bucket.rkt

Add Two Bucket exercise

---

config.json
exercises/practice/run-length-encoding/.docs/instructions.md
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/run-length-encoding/.meta/example.rkt
exercises/practice/run-length-encoding/.meta/tests.toml
exercises/practice/run-length-encoding/run-length-encoding-test.rkt
exercises/practice/run-length-encoding/run-length-encoding.rkt

Run-length encoding in Racket.

Add run-length encoding exercise

---

config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/example.rkt
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/knapsack-test.rkt
exercises/practice/knapsack/knapsack.rkt

Add knapsack exercise

---

config.json
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/example.rkt
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/pig-latin-test.rkt
exercises/practice/pig-latin/pig-latin.rkt

Pig Latin in Racket

---

config.json
exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/largest-series-product/.meta/example.rkt
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest-series-product-test.rkt
exercises/practice/largest-series-product/largest-series-product.rkt

One more practice exercise for Racket

Largest Series Product for Racket

---

config.json
exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.meta/config.json
exercises/practice/luhn/.meta/example.rkt
exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/luhn-test.rkt
exercises/practice/luhn/luhn.rkt

Add Luhn exercise

---

config.json
exercises/practice/circular-buffer/.docs/instructions.md
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/circular-buffer/.meta/example.rkt
exercises/practice/circular-buffer/.meta/tests.toml
exercises/practice/circular-buffer/circular-buffer-test.rkt
exercises/practice/circular-buffer/circular-buffer.rkt

Add the circular buffer exercise.  This gives a chance to play with classes in Racket.

Circular Buffer for racket

---

config.json
exercises/practice/minesweeper/.docs/instructions.md
exercises/practice/minesweeper/.meta/config.json
exercises/practice/minesweeper/.meta/example.rkt
exercises/practice/minesweeper/.meta/tests.toml
exercises/practice/minesweeper/minesweeper-test.rkt
exercises/practice/minesweeper/minesweeper.rkt

Minesweeper for Racket

---

config.json
exercises/practice/spiral-matrix/.docs/instructions.md
exercises/practice/spiral-matrix/.meta/config.json
exercises/practice/spiral-matrix/.meta/example.rkt
exercises/practice/spiral-matrix/.meta/tests.toml
exercises/practice/spiral-matrix/spiral-matrix-test.rkt
exercises/practice/spiral-matrix/spiral-matrix.rkt

Spiral Matrix for Racket

---

config.json
exercises/practice/food-chain/.docs/instructions.md
exercises/practice/food-chain/.meta/config.json
exercises/practice/food-chain/.meta/example.rkt
exercises/practice/food-chain/.meta/tests.toml
exercises/practice/food-chain/food-chain-test.rkt
exercises/practice/food-chain/food-chain.rkt

Add Food Chain for Racket

---

config.json
exercises/practice/parallel-letter-frequency/.docs/instructions.md
exercises/practice/parallel-letter-frequency/.meta/config.json
exercises/practice/parallel-letter-frequency/.meta/example.rkt
exercises/practice/parallel-letter-frequency/.meta/tests.toml
exercises/practice/parallel-letter-frequency/parallel-letter-frequency-test.rkt
exercises/practice/parallel-letter-frequency/parallel-letter-frequency.rkt

Not sure how much parallelism we actually get from this.

Parallel letter frequency using for/async

---

config.json
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/pascals-triangle/.meta/config.json
exercises/practice/pascals-triangle/.meta/example.rkt
exercises/practice/pascals-triangle/.meta/tests.toml
exercises/practice/pascals-triangle/pascals-triangle-test.rkt
exercises/practice/pascals-triangle/pascals-triangle.rkt

Pascal's triangle for Racket

---

config.json
exercises/practice/kindergarten-garden/.docs/instructions.md
exercises/practice/kindergarten-garden/.meta/config.json
exercises/practice/kindergarten-garden/.meta/example.rkt
exercises/practice/kindergarten-garden/.meta/tests.toml
exercises/practice/kindergarten-garden/kindergarten-garden-test.rkt
exercises/practice/kindergarten-garden/kindergarten-garden.rkt

Kindergarten garden for Racket

---

config.json
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/secret-handshake/.docs/introduction.md
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/secret-handshake/.meta/example.rkt
exercises/practice/secret-handshake/.meta/tests.toml
exercises/practice/secret-handshake/secret-handshake-test.rkt
exercises/practice/secret-handshake/secret-handshake.rkt

This should complete the set of 48in24 exercises for Racket.

Secret Handshake for Racket

---

config.json

Closes #311. I standardized difficulties to 2, 5, and 8. Then I bumped a few difficulties based on the Python and Rust tracks or personal experience.

Standardize difficulties and resort exercises

---

config.json
exercises/practice/bowling/.docs/instructions.md
exercises/practice/bowling/.meta/config.json
exercises/practice/bowling/.meta/example.rkt
exercises/practice/bowling/.meta/tests.toml
exercises/practice/bowling/bowling-test.rkt
exercises/practice/bowling/bowling.rkt

Add Bowling for Racket

---

config.json
exercises/practice/pythagorean-triplets/.meta/config.json
exercises/practice/pythagorean-triplets/.meta/example.rkt
exercises/practice/pythagorean-triplets/pythagorean-triplets-test.rkt
exercises/practice/pythagorean-triplets/pythagorean-triplets.rkt

Pythagorean Triplets for Racket

---

config.json
exercises/practice/flower-field/.docs/instructions.md
exercises/practice/flower-field/.docs/introduction.md
exercises/practice/flower-field/.meta/config.json
exercises/practice/flower-field/.meta/example.rkt
exercises/practice/flower-field/.meta/tests.toml
exercises/practice/flower-field/flower-field-test.rkt
exercises/practice/flower-field/flower-field.rkt

https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967/14

Add `flower-field`

---

exercises/practice/bank-account/.meta/config.json
exercises/practice/bowling/.meta/config.json
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/diamond/.meta/config.json
exercises/practice/food-chain/.meta/config.json
exercises/practice/grade-school/.meta/config.json
exercises/practice/kindergarten-garden/.meta/config.json
exercises/practice/knapsack/.meta/config.json
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/leap/.approaches/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/parallel-letter-frequency/.meta/config.json
exercises/practice/pascals-triangle/.meta/config.json
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pythagorean-triplets/.meta/config.json
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/sieve/.meta/config.json
exercises/practice/spiral-matrix/.meta/config.json
exercises/practice/two-bucket/.meta/config.json
exercises/practice/zebra-puzzle/.meta/config.json

Just the result of running `coniglet mt -uy`

Format exercise configs

---

exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/two-bucket-test.rkt

Sync new `two-bucket` tests
