anagram/anagram-test.rkt, anagram/example.rkt
The Racket style calls for reasonable documentation. Exported functions are ideally 
documented in the provide specification. 
Tests go into submodules named tests. race test can run these submodules from 
the command line.  They are also run automatically when programmers develop from 
within DrRacket. 
NOTE: I have left the (exit ..) call in for now but I consider it completely superfluous. 
I don't know the context of how you will run/use these example and test files, but I 
urge you to check out the raco test command.
=> Racket-y style

accumulate/accumulate-test.rkt, accumulate/accumulate.rkt, accumulate/example.rkt, config.json
Getting my feet wet. Any feedback would be appreciated :)
=> Add the accumulate problem

accumulate/accumulate-test.rkt
Or the run of the test will not show anything (run-rests should be
part of the test module, not of the test-suite).
=> Fix unbalanced parentheses

say/example.rkt, say/say-test.rkt
Because the integer-in contract includes its bounds.
Also, made UPPER-BOUND a computed constant.
=> [say] fix example.rkt upper bound

README.md, SETUP.md
Closes #47.
Though, I am not 100% sure on the new to git link.
=> Remove help.exercism.io references

word-count/word-count-test.rkt
There was a minor problem with 'hashes-equal?'. When actual is empty it would always return #t.
=> hashes-equal? no longer returns #t when actual is empty.

README.md
moved attribution here from exercism.io's ATTRIBUTION.md
a step in fixing https://github.com/exercism/exercism.io/issues/3112.
=> attribute the track icon to its creator

docs/INSTALLATION.md
- Currently homebrew does not included a full "racket" package, only minimal-racket. The full package is available via cask
- Add a note for users of the official installer to enable the CLI tools (needed to follow the instructions on how to run tests)
=> Update installation instructions for OS X

config.json, exercises/acronym/acronym-test.rkt, exercises/acronym/acronym.rkt, exercises/acronym/example.rkt
This patch adds the acronym exercise with stub, tests and an example solution, as per the guidelines. The tests were based on the x-common test data.
=> Add acronym exercise

.travis.yml, README.md
This changes configlet to pass a subcommand.
For now, we've released a version of configlet which handles both the old command:
configlet path/to/track
as well as the new command:
configlet lint path/to/track
This will let us update all the travis files to include the subcommand before we
release the version of configlet that requires the subcommand.
https://github.com/exercism/configlet/pull/23
=> Call configlet subcommand on CI

config/exercise_readme.go.tmpl, exercises/accumulate/README.md, exercises/acronym/README.md, exercises/allergies/README.md, exercises/anagram/README.md, exercises/bob/README.md, exercises/difference-of-squares/README.md, exercises/etl/README.md, exercises/gigasecond/README.md, exercises/grains/README.md, exercises/grep/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/list-ops/README.md, exercises/nucleotide-count/README.md, exercises/perfect-numbers/README.md, exercises/phone-number/README.md, exercises/raindrops/README.md, exercises/rna-transcription/README.md, exercises/roman-numerals/README.md, exercises/say/README.md, exercises/scrabble-score/README.md, exercises/word-count/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
=> Generate static exercise README templates

config.json
The previous version of `configlet uuid` was known to generate invalid UUIDs. The latest release of Configlet [v3.6.1](https://github.com/exercism/configlet/releases) fixes that issue for newly added exercises, but existing exercise UUIDs need to be updated manually.
This change pertains to exercism/configlet#99
=> config.json: Fix invalid exercise UUID

docs/LEARNING.md
At the minute, this link ends up at a page saying "The requested page could not be found".
Looks like they've moved it to a fourth-edition specific page.
=> fix link to little schemer

exercises/difference-of-squares/difference-of-squares-test.rkt, exercises/difference-of-squares/difference-of-squares.rkt, exercises/difference-of-squares/example.rkt
In exercise "difference-of-squares", renamed `square-of-sums` to `square-of-sum`, and `difference of-sums` to `difference-of-squares`.
=> difference-of-squares: renamed square-of-sums to square-of-sum

config.json, exercises/hello-world/example.rkt, exercises/hello-world/hello-world-test.rkt, exercises/two-fer/README.md, exercises/two-fer/example.rkt, exercises/two-fer/two-fer-test.rkt, exercises/two-fer/two-fer.rkt
A decision was made [upstream](https://github.com/exercism/problem-specifications/issues/520) to simplify the hello-world exercise and implement a [new exercise](https://github.com/exercism/problem-specifications/issues/548) to take its place. This PR brings the racket track in line with these new changes.
=> Update hello-world exercise and add two-fer exercise

exercises/leap/leap-test.rkt
I noticed it was possible to have a solution which allowed years like 1800 to sneak through the current suite.  On reading https://github.com/exercism/problem-specifications/blob/master/exercises/leap/canonical-data.json (see also https://github.com/exercism/problem-specifications/commit/3134d31aeebf74374b7aaa11b6f35a8f80fa7b46) I realised our test data had drifted.
=> tests in line with problem specification

config.json
Summary:
- Apply the changes made by running `configlet fmt`.
- Fix typos in the blurb.
I noticed that the Racket track is currently the only track where an exercise is missing the `unlocked_by` key.
Feel free to squash these commits if desired.
=> config.json: Add missing `unlocked_by` keys; Fix blurb typos

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md, exercises/practice/atbash-cipher/.docs/instructions.append.md, exercises/practice/perfect-numbers/.docs/instructions.append.md, exercises/practice/robot-name/.docs/instructions.append.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
=> [v3] Update Markdown files to latest spec

exercises/practice/hello-world/hello-world.rkt
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

exercises/practice/accumulate/accumulate.rkt, exercises/practice/acronym/acronym.rkt, exercises/practice/affine-cipher/affine-cipher.rkt, exercises/practice/all-your-base/all-your-base.rkt, exercises/practice/allergies/allergies.rkt, exercises/practice/anagram/anagram.rkt, exercises/practice/armstrong-numbers/armstrong-numbers.rkt, exercises/practice/atbash-cipher/atbash-cipher.rkt
As mentioned in previous conversation: a stub for each exercise is nice to have as a user can immediately run `raco test .` and the tests will run (and fail) as the code is at least syntactically correct.
here ive updated any/all exercises whose name starts with `a` that needed updating
=> adds or updates for stub implementations which throw an error (for exercises named 'a*')

docs/INSTALLATION.md
The racket-dl link isn't properly formatted on the website so I'm removing the hyperlink
=> Remove link from caution

exercises/practice/collatz-conjecture/.meta/example.rkt, exercises/practice/collatz-conjecture/.meta/tests.toml, exercises/practice/collatz-conjecture/collatz-conjecture-test.rkt
=> Update collatz conjecture

exercises/practice/armstrong-numbers/.meta/tests.toml, exercises/practice/armstrong-numbers/armstrong-numbers-test.rkt
Update test suite to reflect preferred setup in the README
May fix #274
=> Sync tests for armstrong-numbers

exercises/practice/etl/.docs/instructions.md, exercises/practice/gigasecond/.docs/introduction.md, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/rna-transcription/.docs/introduction.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
=> Convert backtick (`) admonition fences to tildes (~)

.github/workflows/ci.yml
Racket 8.10 came out in August, and versions come out every few months. Therefore, it'd make sense to test two versions back instead of one. `stable` is an option here instead of manually specifying the current release, but I don't see aliases for one and two releases back so it'd be confusing to maintain both aliases and explicit version numbers.
=> Run CI on Racket 8.8 - 8.10

config.json, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/binary-search/.docs/introduction.md, exercises/practice/binary-search/.meta/config.json, exercises/practice/binary-search/.meta/example.rkt, exercises/practice/binary-search/.meta/tests.toml, exercises/practice/binary-search/binary-search-test.rkt, exercises/practice/binary-search/binary-search.rkt
Related to #297
I put 2 as difficulty, what do you think?
Is the prototype and naming good (i.e. `binary-search array value`), or should it follow the instruction story (i.e. `find-song-index playlist song`)?
Do not hesitate to tell me there are things to modify @BNAndras. 😉
=> Add binary-search exercise (#297)

config.json, exercises/practice/strain/.docs/instructions.md, exercises/practice/strain/.meta/config.json, exercises/practice/strain/.meta/example.rkt, exercises/practice/strain/.meta/tests.toml, exercises/practice/strain/strain-test.rkt, exercises/practice/strain/strain.rkt
Are these two lambda acceptable? These are the predicates given to the tested function.
For the latter, is it ok to use `list` in this case? The lambda doesn't work with the quote form.
```racket
(test-equal? "keeps strings"
(keep '("apple" "zebra" "banana" "zombies" "cherimoya" "zealot")
(lambda (x) (equal? (string-ref x 0) #\z)))
'("zebra" "zombies" "zealot"))
(test-equal? "keeps lists"
(keep (list '(1 2 3) '(5 5 5) '(5 1 2) '(2 1 2) '(1 5 2) '(2 2 1) '(1 2 5))
(lambda (x) (if (member 5 x) #t #f)))
(list '(5 5 5) '(5 1 2) '(1 5 2) '(1 2 5)))
```
=> Add strain exercise (#297)

exercises/practice/dnd-character/.meta/tests.toml, exercises/practice/dnd-character/dnd-character-test.rkt
I'm adding a track-specific test based on one in the Java track that tests if characters are randomly generated.
I'm removing the test that ability scores should be calculated once. All community solutions so far have used the provided struct, and structs are immutable by default.
I'm rewriting the test for all abilities are within range. The new version has the smaller range for hit points compared to the abilities and doesn't show a partial implementation of how to generate hit points.
=> Update dnd-character tests

exercises/practice/binary-search/.meta/config.json, exercises/practice/binary-search/.meta/example.rkt, exercises/practice/binary-search/binary-search-test.rkt
Additionally, I decided to go ahead and make it return `#f` when the target is not found instead of throwing an error, which is more in line with how the exercise is implemented in other tracks (Common Lisp, Scheme) and `vector-binary-search` in srfi-43: https://docs.racket-lang.org/srfi/srfi-std/srfi-43.html#vector-binary-search
If this later change is not ok, I will revert it.
addresses #323
=> binary-search: use vectors instead of lists for the sorted-data

exercises/practice/collatz-conjecture/.meta/example.rkt, exercises/practice/collatz-conjecture/collatz-conjecture-test.rkt
The previous iteration was strict on testing for a particular error message. This change allows students to idiomatically define a contract on `collatz`, and it won't break solutions that previously passed the last iteration.
=> Update collatz-conjecture tests to allow use of contract

config.json, exercises/practice/yacht/.docs/instructions.md, exercises/practice/yacht/.meta/config.json, exercises/practice/yacht/.meta/example.rkt, exercises/practice/yacht/.meta/tests.toml, exercises/practice/yacht/yacht-test.rkt, exercises/practice/yacht/yacht.rkt
=> Add Yacht exercise

.github/workflows/ci.yml
Once exercism/racket-test-runner#69 is merged, we should update the CI here as well.
=> Bump CI to Racket 8.12

config.json, exercises/practice/diamond/.docs/instructions.md, exercises/practice/diamond/.meta/config.json, exercises/practice/diamond/.meta/example.rkt, exercises/practice/diamond/.meta/tests.toml, exercises/practice/diamond/diamond-test.rkt, exercises/practice/diamond/diamond.rkt
An easy one.  I called the function "rows" because that is what is in the problem specification, although I don't like that name very much.
=> Diamond for Racket

config.json, exercises/practice/robot-simulator/.docs/instructions.md, exercises/practice/robot-simulator/.meta/config.json, exercises/practice/robot-simulator/.meta/example.rkt, exercises/practice/robot-simulator/.meta/tests.toml, exercises/practice/robot-simulator/robot-simulator-test.rkt, exercises/practice/robot-simulator/robot-simulator.rkt
=> Robot simulator for Racket

config.json, exercises/practice/bank-account/.docs/instructions.md, exercises/practice/bank-account/.meta/config.json, exercises/practice/bank-account/.meta/example.rkt, exercises/practice/bank-account/.meta/tests.toml, exercises/practice/bank-account/bank-account-test.rkt, exercises/practice/bank-account/bank-account.rkt
I was happy to see that the concurrent test failed when I took out the semaphore operations.  No guarantee that it will always happen, but at least we are getting some real concurrency.
=> Bank account for Racket

config.json, exercises/practice/grade-school/.docs/instructions.md, exercises/practice/grade-school/.meta/config.json, exercises/practice/grade-school/.meta/example.rkt, exercises/practice/grade-school/.meta/tests.toml, exercises/practice/grade-school/grade-school-test.rkt, exercises/practice/grade-school/grade-school.rkt
This exercise is kind of a mess.  The instructions are vague and I see a lot of variabilty among the different implementations. The canonical data indicates that the roster should throw away the grade levels, but following the example of C++, I have retained them in hash->list format. One of the tests seems flat wrong, and I noticed that other languages skipped it, but I have fixed it to match what seems to be its intent.
=> Grade school for Racket

exercises/practice/binary-search/.docs/instructions.append.md, exercises/practice/binary-search/binary-search-test.rkt
I've added an instructions append to clarify that sorted vectors are being used instead of lists. I've also replaced references to arrays in the test suite. I did some minor formatting and converted a few of the `(test-eqv ... #f)`  tests to the simpler `(test-false ...)` tests
=> Update binary search

.github/workflows/ci.yml
Racket 8.13 was released two days ago and is already available as a snapshot for CI purposes. The test runner will need to wait a few days for a Docker image of 8.13.
=> Bump CI to Racket 8.13

exercises/practice/robot-name/robot-name-test.rkt
The regex also matched on sub strings.
The other tests did not do anything because they only returned a boolean instead of using `check` from rackunit.
=> Fix robot-name tests

.github/workflows/ci.yml
The test runner will also need to be updated once the 8.15 image is available.
=> Update CI to Racket 8.15

exercises/practice/anagram/anagram-test.rkt
Related to #410.
I'm sorting the student's results so they can return the anagrams in any order. This only matters when we have a list with more than one anagram so not all tests are touched. Racket's indent-all added some formatting noise, and I also reformatted the candidates for `detects three anagrams` since that line went a bit long on my screen
=> Make `anagram` order-independent

.github/workflows/ci.yml
Related to https://github.com/exercism/racket-test-runner/pull/87
=> Update CI to Racket 8.16

exercises/practice/luhn/.docs/instructions.md, exercises/practice/protein-translation/.docs/instructions.md
I'm taking care of the docs first and then some of the missing tests separately for `anagram`, `reverse-string`, `say`, `variable-length-quantity`, and `word-count`. `say` will need some retooling since each step is tested as a separate property when it should be a single property being tested throughout. That'll break about 40 completions so that's not too bad especially given we're making the exercise more canonical.
=> Sync problem-specs docs

exercises/practice/say/.meta/config.json, exercises/practice/say/.meta/example.rkt, exercises/practice/say/.meta/tests.toml, exercises/practice/say/say-test.rkt, exercises/practice/say/say.rkt
I rewrote the test suite to reflect the canonical tests upstream which expect a single `say` function. That in turn required me to update the stub and example solution.
=> Sync `say` tests
